/**
 * Created by koushikkrishnan on 2/15/15.
 */
/*** @jsx React.DOM */
var board = new Board();
board.init();
/**
 * Class Rectagle
 * A rectangle will represent one square in the minesweeper board. It has an
 * onClick function that will change its state to be clicked or unclicked and
 * will interact with Board and let it know when a certain element has been
 * clicked.
 */
var Rectangle = React.createClass({
    getInitialState: function() {
        return {fill: "transparent"};
    },
    getBoardX: function(xLoc) {
        var x = xLoc - 30;
        x = x / 40;
        return x;
    },
    getBoardY: function(yLoc) {
        var y = yLoc - 30;
        y = y / 40;
        return y;
    },
    /**
     * The ultimate event handler!!
     *
     * Case: first click
     *      - register the click
     *      - fill the rest of the board with bombs
     * Case: normal left-click
     *      - register the click
     *      - check if bomb exists there
     *          - true: game over


     WHAT TO DO:
     - have Runner handle the clicks -> make edits to the board
     - Rectangles will have 2 properties: row and col
     - they will figure what to display
     */
    handleClick: function() {
        if (board.firstClick) {
            var xLoc = this.props.x;
            var yLoc = this.props.y;
            board.fillBombs( this.getBoardX(xLoc), this.getBoardY(yLoc) );
            board.firstClick = true;
        } else {
            this.setState({fill: "black"});
        }
    },
    render: function() {
        return (
            <rect x={this.props.x} y={this.props.y} width="40" height="40" stroke="red" fill={this.state.fill} strokeWidth="5" />
        )
    }
});

var Runner = React.createClass({
    getInitialState: function() {
        return {
            xLoc: "transparent"
        };
    },
    getBoardX: function(xLoc) {
        var x = xLoc - 30;
        x = x / 40;
        return Math.floor(x);
    },
    getBoardY: function(yLoc) {
        var y = yLoc - 30;
        y = y / 40;
        return Math.floor(y);
    },
    handleClick: function(event) {
        // retrive location in board
        var row = this.getBoardX(event.clientY);
        var col = this.getBoardY(event.clientX);

    },
    render: function() {
        /**
         * NOTE:
         * The following values were generated by a python script. This is
         * my first time using ReactJS and I know there MUST be a better way
         * to this.
         *
         * I just didn't know how to do it any other way.
         */
        return (
            <svg width="700" height="700" version="1.1" xmlns="http://www.w3.org/2000/svg" onClick={this.handleClick}>
                <Rectangle x="30" y="30" />
                <Rectangle x="30" y="70" />
                <Rectangle x="30" y="110" />
                <Rectangle x="30" y="150" />
                <Rectangle x="30" y="190" />
                <Rectangle x="30" y="230" />
                <Rectangle x="30" y="270" />
                <Rectangle x="30" y="310" />
                <Rectangle x="30" y="350" />
                <Rectangle x="30" y="390" />
                <Rectangle x="30" y="430" />
                <Rectangle x="30" y="470" />
                <Rectangle x="30" y="510" />
                <Rectangle x="30" y="550" />
                <Rectangle x="30" y="590" />
                <Rectangle x="30" y="630" />
                <Rectangle x="70" y="30" />
                <Rectangle x="70" y="70" />
                <Rectangle x="70" y="110" />
                <Rectangle x="70" y="150" />
                <Rectangle x="70" y="190" />
                <Rectangle x="70" y="230" />
                <Rectangle x="70" y="270" />
                <Rectangle x="70" y="310" />
                <Rectangle x="70" y="350" />
                <Rectangle x="70" y="390" />
                <Rectangle x="70" y="430" />
                <Rectangle x="70" y="470" />
                <Rectangle x="70" y="510" />
                <Rectangle x="70" y="550" />
                <Rectangle x="70" y="590" />
                <Rectangle x="70" y="630" />
                <Rectangle x="110" y="30" />
                <Rectangle x="110" y="70" />
                <Rectangle x="110" y="110" />
                <Rectangle x="110" y="150" />
                <Rectangle x="110" y="190" />
                <Rectangle x="110" y="230" />
                <Rectangle x="110" y="270" />
                <Rectangle x="110" y="310" />
                <Rectangle x="110" y="350" />
                <Rectangle x="110" y="390" />
                <Rectangle x="110" y="430" />
                <Rectangle x="110" y="470" />
                <Rectangle x="110" y="510" />
                <Rectangle x="110" y="550" />
                <Rectangle x="110" y="590" />
                <Rectangle x="110" y="630" />
                <Rectangle x="150" y="30" />
                <Rectangle x="150" y="70" />
                <Rectangle x="150" y="110" />
                <Rectangle x="150" y="150" />
                <Rectangle x="150" y="190" />
                <Rectangle x="150" y="230" />
                <Rectangle x="150" y="270" />
                <Rectangle x="150" y="310" />
                <Rectangle x="150" y="350" />
                <Rectangle x="150" y="390" />
                <Rectangle x="150" y="430" />
                <Rectangle x="150" y="470" />
                <Rectangle x="150" y="510" />
                <Rectangle x="150" y="550" />
                <Rectangle x="150" y="590" />
                <Rectangle x="150" y="630" />
                <Rectangle x="190" y="30" />
                <Rectangle x="190" y="70" />
                <Rectangle x="190" y="110" />
                <Rectangle x="190" y="150" />
                <Rectangle x="190" y="190" />
                <Rectangle x="190" y="230" />
                <Rectangle x="190" y="270" />
                <Rectangle x="190" y="310" />
                <Rectangle x="190" y="350" />
                <Rectangle x="190" y="390" />
                <Rectangle x="190" y="430" />
                <Rectangle x="190" y="470" />
                <Rectangle x="190" y="510" />
                <Rectangle x="190" y="550" />
                <Rectangle x="190" y="590" />
                <Rectangle x="190" y="630" />
                <Rectangle x="230" y="30" />
                <Rectangle x="230" y="70" />
                <Rectangle x="230" y="110" />
                <Rectangle x="230" y="150" />
                <Rectangle x="230" y="190" />
                <Rectangle x="230" y="230" />
                <Rectangle x="230" y="270" />
                <Rectangle x="230" y="310" />
                <Rectangle x="230" y="350" />
                <Rectangle x="230" y="390" />
                <Rectangle x="230" y="430" />
                <Rectangle x="230" y="470" />
                <Rectangle x="230" y="510" />
                <Rectangle x="230" y="550" />
                <Rectangle x="230" y="590" />
                <Rectangle x="230" y="630" />
                <Rectangle x="270" y="30" />
                <Rectangle x="270" y="70" />
                <Rectangle x="270" y="110" />
                <Rectangle x="270" y="150" />
                <Rectangle x="270" y="190" />
                <Rectangle x="270" y="230" />
                <Rectangle x="270" y="270" />
                <Rectangle x="270" y="310" />
                <Rectangle x="270" y="350" />
                <Rectangle x="270" y="390" />
                <Rectangle x="270" y="430" />
                <Rectangle x="270" y="470" />
                <Rectangle x="270" y="510" />
                <Rectangle x="270" y="550" />
                <Rectangle x="270" y="590" />
                <Rectangle x="270" y="630" />
                <Rectangle x="310" y="30" />
                <Rectangle x="310" y="70" />
                <Rectangle x="310" y="110" />
                <Rectangle x="310" y="150" />
                <Rectangle x="310" y="190" />
                <Rectangle x="310" y="230" />
                <Rectangle x="310" y="270" />
                <Rectangle x="310" y="310" />
                <Rectangle x="310" y="350" />
                <Rectangle x="310" y="390" />
                <Rectangle x="310" y="430" />
                <Rectangle x="310" y="470" />
                <Rectangle x="310" y="510" />
                <Rectangle x="310" y="550" />
                <Rectangle x="310" y="590" />
                <Rectangle x="310" y="630" />
                <Rectangle x="350" y="30" />
                <Rectangle x="350" y="70" />
                <Rectangle x="350" y="110" />
                <Rectangle x="350" y="150" />
                <Rectangle x="350" y="190" />
                <Rectangle x="350" y="230" />
                <Rectangle x="350" y="270" />
                <Rectangle x="350" y="310" />
                <Rectangle x="350" y="350" />
                <Rectangle x="350" y="390" />
                <Rectangle x="350" y="430" />
                <Rectangle x="350" y="470" />
                <Rectangle x="350" y="510" />
                <Rectangle x="350" y="550" />
                <Rectangle x="350" y="590" />
                <Rectangle x="350" y="630" />
                <Rectangle x="390" y="30" />
                <Rectangle x="390" y="70" />
                <Rectangle x="390" y="110" />
                <Rectangle x="390" y="150" />
                <Rectangle x="390" y="190" />
                <Rectangle x="390" y="230" />
                <Rectangle x="390" y="270" />
                <Rectangle x="390" y="310" />
                <Rectangle x="390" y="350" />
                <Rectangle x="390" y="390" />
                <Rectangle x="390" y="430" />
                <Rectangle x="390" y="470" />
                <Rectangle x="390" y="510" />
                <Rectangle x="390" y="550" />
                <Rectangle x="390" y="590" />
                <Rectangle x="390" y="630" />
                <Rectangle x="430" y="30" />
                <Rectangle x="430" y="70" />
                <Rectangle x="430" y="110" />
                <Rectangle x="430" y="150" />
                <Rectangle x="430" y="190" />
                <Rectangle x="430" y="230" />
                <Rectangle x="430" y="270" />
                <Rectangle x="430" y="310" />
                <Rectangle x="430" y="350" />
                <Rectangle x="430" y="390" />
                <Rectangle x="430" y="430" />
                <Rectangle x="430" y="470" />
                <Rectangle x="430" y="510" />
                <Rectangle x="430" y="550" />
                <Rectangle x="430" y="590" />
                <Rectangle x="430" y="630" />
                <Rectangle x="470" y="30" />
                <Rectangle x="470" y="70" />
                <Rectangle x="470" y="110" />
                <Rectangle x="470" y="150" />
                <Rectangle x="470" y="190" />
                <Rectangle x="470" y="230" />
                <Rectangle x="470" y="270" />
                <Rectangle x="470" y="310" />
                <Rectangle x="470" y="350" />
                <Rectangle x="470" y="390" />
                <Rectangle x="470" y="430" />
                <Rectangle x="470" y="470" />
                <Rectangle x="470" y="510" />
                <Rectangle x="470" y="550" />
                <Rectangle x="470" y="590" />
                <Rectangle x="470" y="630" />
                <Rectangle x="510" y="30" />
                <Rectangle x="510" y="70" />
                <Rectangle x="510" y="110" />
                <Rectangle x="510" y="150" />
                <Rectangle x="510" y="190" />
                <Rectangle x="510" y="230" />
                <Rectangle x="510" y="270" />
                <Rectangle x="510" y="310" />
                <Rectangle x="510" y="350" />
                <Rectangle x="510" y="390" />
                <Rectangle x="510" y="430" />
                <Rectangle x="510" y="470" />
                <Rectangle x="510" y="510" />
                <Rectangle x="510" y="550" />
                <Rectangle x="510" y="590" />
                <Rectangle x="510" y="630" />
                <Rectangle x="550" y="30" />
                <Rectangle x="550" y="70" />
                <Rectangle x="550" y="110" />
                <Rectangle x="550" y="150" />
                <Rectangle x="550" y="190" />
                <Rectangle x="550" y="230" />
                <Rectangle x="550" y="270" />
                <Rectangle x="550" y="310" />
                <Rectangle x="550" y="350" />
                <Rectangle x="550" y="390" />
                <Rectangle x="550" y="430" />
                <Rectangle x="550" y="470" />
                <Rectangle x="550" y="510" />
                <Rectangle x="550" y="550" />
                <Rectangle x="550" y="590" />
                <Rectangle x="550" y="630" />
                <Rectangle x="590" y="30" />
                <Rectangle x="590" y="70" />
                <Rectangle x="590" y="110" />
                <Rectangle x="590" y="150" />
                <Rectangle x="590" y="190" />
                <Rectangle x="590" y="230" />
                <Rectangle x="590" y="270" />
                <Rectangle x="590" y="310" />
                <Rectangle x="590" y="350" />
                <Rectangle x="590" y="390" />
                <Rectangle x="590" y="430" />
                <Rectangle x="590" y="470" />
                <Rectangle x="590" y="510" />
                <Rectangle x="590" y="550" />
                <Rectangle x="590" y="590" />
                <Rectangle x="590" y="630" />
                <Rectangle x="630" y="30" />
                <Rectangle x="630" y="70" />
                <Rectangle x="630" y="110" />
                <Rectangle x="630" y="150" />
                <Rectangle x="630" y="190" />
                <Rectangle x="630" y="230" />
                <Rectangle x="630" y="270" />
                <Rectangle x="630" y="310" />
                <Rectangle x="630" y="350" />
                <Rectangle x="630" y="390" />
                <Rectangle x="630" y="430" />
                <Rectangle x="630" y="470" />
                <Rectangle x="630" y="510" />
                <Rectangle x="630" y="550" />
                <Rectangle x="630" y="590" />
                <Rectangle x="630" y="630" />
            </svg>
        )
    }
})

React.renderComponent(<Runner />, document.getElementById("content"));
