/*** @jsx React.DOM */

/**
 * Class Rectagle
 * A rectangle will represent one square in the minesweeper board. It has an
 * onClick function that will change its state to be clicked or unclicked and
 * will interact with Board and let it know when a certain element has been
 * clicked.
 */
var Rectangle = React.createClass({
    getInitialState: function() {
        return {fill: "transparent"};
    },
    handleClick: function() {
        this.setState({fill: "black"})
    },
    render: function() {
        return (
            <rect x={this.props.x} y={this.props.y} width="40" height="40" stroke="red" fill={this.state.fill} strokeWidth="5" onClick={this.handleClick} />
        )
    }
});

var Runner = React.createClass({
    render: function() {
        return (
            <svg width="700" height="700" version="1.1" xmlns="http://www.w3.org/2000/svg">
            /**
             * NOTE:
             * The following values were generated by a python script. This is
             * my first time using ReactJS and I know there MUST be a better way
             * to this.
             *
             * I just didn't know how to do it any other way.
             */
            <Rectangle x="30" y="30" />
            <Rectangle x="30" y="70" />
            <Rectangle x="30" y="110" />
            <Rectangle x="30" y="150" />
            <Rectangle x="30" y="190" />
            <Rectangle x="30" y="230" />
            <Rectangle x="30" y="270" />
            <Rectangle x="30" y="310" />
            <Rectangle x="30" y="350" />
            <Rectangle x="30" y="390" />
            <Rectangle x="30" y="430" />
            <Rectangle x="30" y="470" />
            <Rectangle x="30" y="510" />
            <Rectangle x="30" y="550" />
            <Rectangle x="30" y="590" />
            <Rectangle x="30" y="630" />
            <Rectangle x="70" y="30" />
            <Rectangle x="70" y="70" />
            <Rectangle x="70" y="110" />
            <Rectangle x="70" y="150" />
            <Rectangle x="70" y="190" />
            <Rectangle x="70" y="230" />
            <Rectangle x="70" y="270" />
            <Rectangle x="70" y="310" />
            <Rectangle x="70" y="350" />
            <Rectangle x="70" y="390" />
            <Rectangle x="70" y="430" />
            <Rectangle x="70" y="470" />
            <Rectangle x="70" y="510" />
            <Rectangle x="70" y="550" />
            <Rectangle x="70" y="590" />
            <Rectangle x="70" y="630" />
            <Rectangle x="110" y="30" />
            <Rectangle x="110" y="70" />
            <Rectangle x="110" y="110" />
            <Rectangle x="110" y="150" />
            <Rectangle x="110" y="190" />
            <Rectangle x="110" y="230" />
            <Rectangle x="110" y="270" />
            <Rectangle x="110" y="310" />
            <Rectangle x="110" y="350" />
            <Rectangle x="110" y="390" />
            <Rectangle x="110" y="430" />
            <Rectangle x="110" y="470" />
            <Rectangle x="110" y="510" />
            <Rectangle x="110" y="550" />
            <Rectangle x="110" y="590" />
            <Rectangle x="110" y="630" />
            <Rectangle x="150" y="30" />
            <Rectangle x="150" y="70" />
            <Rectangle x="150" y="110" />
            <Rectangle x="150" y="150" />
            <Rectangle x="150" y="190" />
            <Rectangle x="150" y="230" />
            <Rectangle x="150" y="270" />
            <Rectangle x="150" y="310" />
            <Rectangle x="150" y="350" />
            <Rectangle x="150" y="390" />
            <Rectangle x="150" y="430" />
            <Rectangle x="150" y="470" />
            <Rectangle x="150" y="510" />
            <Rectangle x="150" y="550" />
            <Rectangle x="150" y="590" />
            <Rectangle x="150" y="630" />
            <Rectangle x="190" y="30" />
            <Rectangle x="190" y="70" />
            <Rectangle x="190" y="110" />
            <Rectangle x="190" y="150" />
            <Rectangle x="190" y="190" />
            <Rectangle x="190" y="230" />
            <Rectangle x="190" y="270" />
            <Rectangle x="190" y="310" />
            <Rectangle x="190" y="350" />
            <Rectangle x="190" y="390" />
            <Rectangle x="190" y="430" />
            <Rectangle x="190" y="470" />
            <Rectangle x="190" y="510" />
            <Rectangle x="190" y="550" />
            <Rectangle x="190" y="590" />
            <Rectangle x="190" y="630" />
            <Rectangle x="230" y="30" />
            <Rectangle x="230" y="70" />
            <Rectangle x="230" y="110" />
            <Rectangle x="230" y="150" />
            <Rectangle x="230" y="190" />
            <Rectangle x="230" y="230" />
            <Rectangle x="230" y="270" />
            <Rectangle x="230" y="310" />
            <Rectangle x="230" y="350" />
            <Rectangle x="230" y="390" />
            <Rectangle x="230" y="430" />
            <Rectangle x="230" y="470" />
            <Rectangle x="230" y="510" />
            <Rectangle x="230" y="550" />
            <Rectangle x="230" y="590" />
            <Rectangle x="230" y="630" />
            <Rectangle x="270" y="30" />
            <Rectangle x="270" y="70" />
            <Rectangle x="270" y="110" />
            <Rectangle x="270" y="150" />
            <Rectangle x="270" y="190" />
            <Rectangle x="270" y="230" />
            <Rectangle x="270" y="270" />
            <Rectangle x="270" y="310" />
            <Rectangle x="270" y="350" />
            <Rectangle x="270" y="390" />
            <Rectangle x="270" y="430" />
            <Rectangle x="270" y="470" />
            <Rectangle x="270" y="510" />
            <Rectangle x="270" y="550" />
            <Rectangle x="270" y="590" />
            <Rectangle x="270" y="630" />
            <Rectangle x="310" y="30" />
            <Rectangle x="310" y="70" />
            <Rectangle x="310" y="110" />
            <Rectangle x="310" y="150" />
            <Rectangle x="310" y="190" />
            <Rectangle x="310" y="230" />
            <Rectangle x="310" y="270" />
            <Rectangle x="310" y="310" />
            <Rectangle x="310" y="350" />
            <Rectangle x="310" y="390" />
            <Rectangle x="310" y="430" />
            <Rectangle x="310" y="470" />
            <Rectangle x="310" y="510" />
            <Rectangle x="310" y="550" />
            <Rectangle x="310" y="590" />
            <Rectangle x="310" y="630" />
            <Rectangle x="350" y="30" />
            <Rectangle x="350" y="70" />
            <Rectangle x="350" y="110" />
            <Rectangle x="350" y="150" />
            <Rectangle x="350" y="190" />
            <Rectangle x="350" y="230" />
            <Rectangle x="350" y="270" />
            <Rectangle x="350" y="310" />
            <Rectangle x="350" y="350" />
            <Rectangle x="350" y="390" />
            <Rectangle x="350" y="430" />
            <Rectangle x="350" y="470" />
            <Rectangle x="350" y="510" />
            <Rectangle x="350" y="550" />
            <Rectangle x="350" y="590" />
            <Rectangle x="350" y="630" />
            <Rectangle x="390" y="30" />
            <Rectangle x="390" y="70" />
            <Rectangle x="390" y="110" />
            <Rectangle x="390" y="150" />
            <Rectangle x="390" y="190" />
            <Rectangle x="390" y="230" />
            <Rectangle x="390" y="270" />
            <Rectangle x="390" y="310" />
            <Rectangle x="390" y="350" />
            <Rectangle x="390" y="390" />
            <Rectangle x="390" y="430" />
            <Rectangle x="390" y="470" />
            <Rectangle x="390" y="510" />
            <Rectangle x="390" y="550" />
            <Rectangle x="390" y="590" />
            <Rectangle x="390" y="630" />
            <Rectangle x="430" y="30" />
            <Rectangle x="430" y="70" />
            <Rectangle x="430" y="110" />
            <Rectangle x="430" y="150" />
            <Rectangle x="430" y="190" />
            <Rectangle x="430" y="230" />
            <Rectangle x="430" y="270" />
            <Rectangle x="430" y="310" />
            <Rectangle x="430" y="350" />
            <Rectangle x="430" y="390" />
            <Rectangle x="430" y="430" />
            <Rectangle x="430" y="470" />
            <Rectangle x="430" y="510" />
            <Rectangle x="430" y="550" />
            <Rectangle x="430" y="590" />
            <Rectangle x="430" y="630" />
            <Rectangle x="470" y="30" />
            <Rectangle x="470" y="70" />
            <Rectangle x="470" y="110" />
            <Rectangle x="470" y="150" />
            <Rectangle x="470" y="190" />
            <Rectangle x="470" y="230" />
            <Rectangle x="470" y="270" />
            <Rectangle x="470" y="310" />
            <Rectangle x="470" y="350" />
            <Rectangle x="470" y="390" />
            <Rectangle x="470" y="430" />
            <Rectangle x="470" y="470" />
            <Rectangle x="470" y="510" />
            <Rectangle x="470" y="550" />
            <Rectangle x="470" y="590" />
            <Rectangle x="470" y="630" />
            <Rectangle x="510" y="30" />
            <Rectangle x="510" y="70" />
            <Rectangle x="510" y="110" />
            <Rectangle x="510" y="150" />
            <Rectangle x="510" y="190" />
            <Rectangle x="510" y="230" />
            <Rectangle x="510" y="270" />
            <Rectangle x="510" y="310" />
            <Rectangle x="510" y="350" />
            <Rectangle x="510" y="390" />
            <Rectangle x="510" y="430" />
            <Rectangle x="510" y="470" />
            <Rectangle x="510" y="510" />
            <Rectangle x="510" y="550" />
            <Rectangle x="510" y="590" />
            <Rectangle x="510" y="630" />
            <Rectangle x="550" y="30" />
            <Rectangle x="550" y="70" />
            <Rectangle x="550" y="110" />
            <Rectangle x="550" y="150" />
            <Rectangle x="550" y="190" />
            <Rectangle x="550" y="230" />
            <Rectangle x="550" y="270" />
            <Rectangle x="550" y="310" />
            <Rectangle x="550" y="350" />
            <Rectangle x="550" y="390" />
            <Rectangle x="550" y="430" />
            <Rectangle x="550" y="470" />
            <Rectangle x="550" y="510" />
            <Rectangle x="550" y="550" />
            <Rectangle x="550" y="590" />
            <Rectangle x="550" y="630" />
            <Rectangle x="590" y="30" />
            <Rectangle x="590" y="70" />
            <Rectangle x="590" y="110" />
            <Rectangle x="590" y="150" />
            <Rectangle x="590" y="190" />
            <Rectangle x="590" y="230" />
            <Rectangle x="590" y="270" />
            <Rectangle x="590" y="310" />
            <Rectangle x="590" y="350" />
            <Rectangle x="590" y="390" />
            <Rectangle x="590" y="430" />
            <Rectangle x="590" y="470" />
            <Rectangle x="590" y="510" />
            <Rectangle x="590" y="550" />
            <Rectangle x="590" y="590" />
            <Rectangle x="590" y="630" />
            <Rectangle x="630" y="30" />
            <Rectangle x="630" y="70" />
            <Rectangle x="630" y="110" />
            <Rectangle x="630" y="150" />
            <Rectangle x="630" y="190" />
            <Rectangle x="630" y="230" />
            <Rectangle x="630" y="270" />
            <Rectangle x="630" y="310" />
            <Rectangle x="630" y="350" />
            <Rectangle x="630" y="390" />
            <Rectangle x="630" y="430" />
            <Rectangle x="630" y="470" />
            <Rectangle x="630" y="510" />
            <Rectangle x="630" y="550" />
            <Rectangle x="630" y="590" />
            <Rectangle x="630" y="630" />
            </svg>
        )
    }
})

React.renderComponent(<Runner />, document.getElementById("content"));
